name: CI
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo test --no-default-features
      - run: cargo test --no-default-features -F unstable
      - run: cargo test --no-default-features -F alloc
      - run: cargo test --no-default-features -F alloc,unstable
      - run: cargo test --no-default-features -F std
      - run: cargo test
